query customer_getAll($skip: Int, $take: Int, $where: CustomerDtoFilterInput, $order: [CustomerDtoSortInput!]) {
	customer_getAll {
		result(skip: $skip, take: $take, where: $where, order: $order) {
			items {
				code
				firstName
				gender
				id
				lastName
				phoneNumber
				profileImageUrl
				isBlocked
			}
			totalCount
		}
		status
	}
}
