mutation neighborhood_create($input: CreateNeighborhoodInput!) {
	neighborhood_create(input: $input) {
		status
		result {
			id
			name
		}
	}
}

mutation neighborhood_update($input: UpdateNeighborhoodInput!) {
	neighborhood_update(input: $input) {
		status
		result {
			id
			name
		}
	}
}

mutation neighborhood_delete($input: DeleteNeighborhoodInput!) {
	neighborhood_delete(input: $input) {
		status
	}
}

query neighborhood_getAll(
	$skip: Int
	$take: Int
	$where: NeighborhoodDtoFilterInput
	$order: [NeighborhoodDtoSortInput!]
) {
	neighborhood_getAll {
		result(skip: $skip, take: $take, where: $where, order: $order) {
			items {
				id
				name
				city {
					id
					name
				}
			}
			totalCount
		}
		status
	}
}
